services:
  backend:
    build:
      args:
        USE_GPU: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
